hard_task: ' (a -> <>b)  && (a -> <>c) && (a -> <>f) &&  (a -> <>d) && [](b ->  X(loaded && (!c && !d && !f) U (e && unloaded))) && [](c ->  X(loaded && (!b && !d && !f) U (e && unloaded))) && [](f ->  X(loaded && (!b && !c && !d) U (e && unloaded)))  && [](d ->  X(loaded && (!b && !c && !f) U (e && unloaded))) '
soft_task: ""
